version: "3.1"
services:
  # --------------------------------------
  # Redis
  # --------------------------------------
  redis:
    image: redis:alpine
    container_name: redis
  # --------------------------------------
  # Postgres
  # --------------------------------------
  postgres:
    image: postgres
    container_name: postgres
    volumes:
        - "./src/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - sao_network
  # --------------------------------------
  # Nginx
  # --------------------------------------
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
        - ./application:/application
        - ./src/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - sao_network
  # --------------------------------------
  # Php-fpm
  # --------------------------------------
  php-fpm:
    build: src/php-fpm
    container_name: php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./src/php-fpm/php-local.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - postgres
    networks:
      - sao_network

networks:
  sao_network:
    driver: bridge
